// Libraries
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

public class loginFrame extends javax.swing.JFrame {

    // Variables for mouse position
    int mousepX;
    int mousepY;

    public loginFrame() {
        initComponents();
        conn.myconnection(); // Calls myconnection method

        CenteredFrame(this);
        
        // Initialize background of username and password TEXT FIELD
        usernameField.setBackground(new java.awt.Color(249, 249, 249));
        passwordField.setBackground(new java.awt.Color(249, 249, 249));

        // Replacing the password asterisks to dots
        passwordField.setEchoChar('\u25CF');

        // Hide password (eye) icons
        showPassword.setVisible(false);
        hidePassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane = new javax.swing.JOptionPane();
        parentPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        childPanel = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        showPassword = new javax.swing.JLabel();
        hidePassword = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        LoginLabel = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        forgotLabel = new javax.swing.JLabel();

        jOptionPane.setBackground(new java.awt.Color(249, 249, 249));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Πληροφοριακό Σύστημα");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 460));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parentPanel.setBackground(new java.awt.Color(22, 30, 42));
        parentPanel.setMaximumSize(new java.awt.Dimension(400, 460));
        parentPanel.setMinimumSize(new java.awt.Dimension(400, 460));
        parentPanel.setPreferredSize(new java.awt.Dimension(400, 460));
        parentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(249, 251, 251));
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitButton.setText("x");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
        });
        parentPanel.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 45, 35));
        exitButton.getAccessibleContext().setAccessibleName("Exit Button");
        exitButton.getAccessibleContext().setAccessibleDescription("Exit Button");

        childPanel.setBackground(new java.awt.Color(249, 249, 249));
        childPanel.setMaximumSize(new java.awt.Dimension(400, 410));
        childPanel.setMinimumSize(new java.awt.Dimension(400, 410));
        childPanel.setPreferredSize(new java.awt.Dimension(400, 410));
        childPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameField.setBackground(new java.awt.Color(249, 249, 249));
        usernameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameField.setForeground(new java.awt.Color(51, 51, 51));
        usernameField.setText("Enter username or email address");
        usernameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(229, 229, 229)));
        usernameField.setCaretColor(new java.awt.Color(51, 51, 51));
        usernameField.setOpaque(false);
        usernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFieldFocusLost(evt);
            }
        });
        childPanel.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 250, -1));

        showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_eye_20px.png"))); // NOI18N
        showPassword.setToolTipText("Show password");
        showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                showPasswordMousePressed(evt);
            }
        });
        childPanel.add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 250, -1, -1));
        showPassword.getAccessibleContext().setAccessibleName("showPassword");

        hidePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_hide_20px.png"))); // NOI18N
        hidePassword.setToolTipText("Hide password");
        hidePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hidePasswordMousePressed(evt);
            }
        });
        childPanel.add(hidePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 250, -1, -1));

        passwordField.setBackground(new java.awt.Color(249, 249, 249));
        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(51, 51, 51));
        passwordField.setText("Enter password");
        passwordField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(229, 229, 229)));
        passwordField.setCaretColor(new java.awt.Color(51, 51, 51));
        passwordField.setOpaque(false);
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordFieldKeyTyped(evt);
            }
        });
        childPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 250, -1));

        LoginLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(22, 30, 42));
        LoginLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon.png"))); // NOI18N
        LoginLabel.setText(" Welcome");
        childPanel.add(LoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        LoginButton.setBackground(new java.awt.Color(255, 51, 51));
        LoginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Log in");
        LoginButton.setBorder(null);
        LoginButton.setBorderPainted(false);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.setFocusPainted(false);
        LoginButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        childPanel.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 250, 40));

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLabel.setText("Username or email address");
        childPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordLabel.setText("Password");
        childPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        copyrightLabel.setText("Copyright© 2021 TBD. All Rights Reserved");
        childPanel.add(copyrightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        forgotLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        forgotLabel.setForeground(new java.awt.Color(0, 102, 204));
        forgotLabel.setText("Forgot password?");
        forgotLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        childPanel.add(forgotLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        parentPanel.add(childPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 410));

        getContentPane().add(parentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        doLogin();
    }//GEN-LAST:event_LoginButtonActionPerformed

    public void CenteredFrame(javax.swing.JFrame objFrame) {
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY);
    }
    
    // Drag with mouse
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - mousepX, y - mousepY);
    }//GEN-LAST:event_formMouseDragged

    //  Get mouse potition when mouse is pressed
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    // Remove text inside username TEXT FIELD when focus gained
    private void usernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusGained
        // TODO add your handling code here:
        if (usernameField.getText().equals("Enter username or email address")) {
            usernameField.setText("");
        }
    }//GEN-LAST:event_usernameFieldFocusGained

    // Remove text inside password TEXT FIELD when focus gained
    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusGained
        // TODO add your handling code here:
        if (passwordField.getText().equals("Enter password")) {
            passwordField.setText("");

            // Make [show]password eye icon invisible
            showPassword.setVisible(false);
        }
    }//GEN-LAST:event_passwordFieldFocusGained

    // [X] mouse over effects
    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        // TODO add your handling code here:
        exitButton.setOpaque(true);
        exitButton.setBackground(new Color(255, 51, 51));
        exitButton.setToolTipText("Close");
    }//GEN-LAST:event_exitButtonMouseEntered

    // [X] mouse out effects
    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        // TODO add your handling code here:
        exitButton.setOpaque(false);
        exitButton.setBackground(new Color(0, 0, 0, 0));
        exitButton.setToolTipText("");
    }//GEN-LAST:event_exitButtonMouseExited

    // Username TEXT FIELD "reverts" to default state [showing input message]
    private void usernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusLost
        // TODO add your handling code here:
        if (usernameField.getText().equals("")) {
            usernameField.setText("Enter username or email address");
        }
    }//GEN-LAST:event_usernameFieldFocusLost

    // Password TEXT FIELD "reverts" to default state [showing input message]
    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        // TODO add your handling code here:
        if (passwordField.getText().equals("")) {
            passwordField.setText("Enter password");

            // Make [show]password eye icon invisible
            showPassword.setVisible(false);
        }
    }//GEN-LAST:event_passwordFieldFocusLost

    // Make [show]password icon visible when user starts typing in password TEXT FIELD
    private void passwordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyTyped
        // TODO add your handling code here:
        if (hidePassword.isVisible() == true)
            showPassword.setVisible(false);
        else
            showPassword.setVisible(true);
    }//GEN-LAST:event_passwordFieldKeyTyped

    // Close program when [X] is clicked 
    private void exitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonMousePressed

    // Show password
    private void showPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordMousePressed
        // TODO add your handling code here:
        passwordField.setEchoChar((char) 0); // Show password String
        showPassword.setVisible(false);
        hidePassword.setVisible(true);
    }//GEN-LAST:event_showPasswordMousePressed

    // Hide password
    private void hidePasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidePasswordMousePressed
        // TODO add your handling code here:
        passwordField.setEchoChar('\u25CF'); // Hide password String
        showPassword.setVisible(true);
        hidePassword.setVisible(false);
    }//GEN-LAST:event_hidePasswordMousePressed
        
    private void doLogin(){
        String selectString = "SELECT * FROM checkuser(?,?) ";
        try {
            checkAccount = conn.dbConnection.prepareStatement(selectString);

            checkAccount.setString(1, usernameField.getText());
            checkAccount.setString(2, passwordField.getText());

            rs = checkAccount.executeQuery();

            if (rs.next()) {
                // Open new window
                if (rs.getString(1).equals("admin")) {
                    adminFrame af = new adminFrame();
                    af.setVisible(true);
                    af.pack();
                    af.setLocationRelativeTo(null);
                } else {
                    teacherFrame tf = new teacherFrame();
                    tf.setVisible(true);
                    tf.pack();
                    tf.setLocationRelativeTo(null);
                }
                // Display welcome message to user after a successful login
                JOptionPane.showMessageDialog(null, "Welcome, " + rs.getString(1) + ".");
                System.out.println("\nWelcome back, " + rs.getString(1) + ".\n");
                // Close current window
                this.dispose();
            } else {
                // Inform user via UI | Make them red color
                usernameLabel.setForeground(Color.red);
                usernameLabel.setFont(new Font("Segoe UI", Font.ITALIC, 14));
                usernameField.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));

                passwordLabel.setForeground(Color.red);
                passwordLabel.setFont(new Font("Segoe UI", Font.ITALIC, 14));
                passwordField.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red));

                // Display error message to user
                JOptionPane.showMessageDialog(null, "Invalid username or password.");
            }
        } catch (SQLException ex) {
            System.out.println("\n -- Login SQL Exception --- \n");
            while (ex != null) {
                System.out.println("Message: " + ex.getMessage());
                ex = ex.getNextException();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginFrame().setVisible(true);
            }
        });
    }

    static PreparedStatement checkAccount = null;
    static Statement statement = null;
    static ResultSet rs = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JPanel childPanel;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel forgotLabel;
    private javax.swing.JLabel hidePassword;
    private javax.swing.JOptionPane jOptionPane;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel showPassword;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
